services:
  tracker-app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: cmd/trackerapp/Dockerfile
    container_name: "main-app"
    ports:
      - "8080:8080"
    depends_on:
      - data-base

  data-base:
    image: postgres:18.3-bookworm
    container_name: "DataBase"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql
    restart: always

  migrate:
    image: migrate/migrate:v4.19.1
    container_name: migrate-container
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations

  forwarder-port:
    image: alpine/socat:1.8.0.3
    container_name: expanses-tracker-postgres-forwarder-port
    command: "tcp-listen:5432,fork,reuseaddr tcp-connect:data-base:5432"
    ports:
      - "127.0.0.1:5432:5432"